### ISSUE TITLE
Optimize entire library in a background process?

### ISSUE THREAD

**Issue by malchata** [kamsar/Dianoga#16]
More of a question than a feature request, but I'm wondering if there's a way to optimize the entire media library in the background so we can avoid the issues that can come with generating optimized images on the fly (non-optimal results on first request with async/waiting for optimized images on first request with sync). Is there a gist or utility class that can be used to accomplish this sort of thing on demand?

**Comment by kamsar** [comment]
If you are using the sitecore resizing stuff then not really. Because they
are resized at runtime (losing static optimization in the process), so must
the optimization be. Sitecore resizing is a good solution because the views
can bound image sizes in case a careless editor uploads an unoptimized
image (e.g. Too large dimensions, or like a quality 100 jpeg) to prevent
breaking the site or slowing it down.

If you want to optimize the base version of things in the media library you
could either optimize prior to upload (probably the best results) or look
into some of the other optimization libraries for sitecore that do base
version optimization.
