### ISSUE TITLE
When Dainoga enabled we are facing "unable to decode image 'image/webp'" issue in IE,Edge,Firefox

### ISSUE THREAD

**Issue by kudumulanarenderreddy** [kamsar/Dianoga#42]
When Dainoga enabled we are facing "unable to decode image 'image/webp'" issue in IE,Edge,Firefox.
Could you please provide solution for this.

**Comment by Halling69** [comment]
Hi, I think I've closed in on the problem.

When an image is served to a webp-enabled browser its stored as a webp binary .

But in the sitecore media cache images are stored by itemid (folder) and querystring [Key] in the .ini file

both itemid and [Key] match when a request arrives from a non webp enabled browser, and the webp image is served.

I think it needs to be fixed with an override of the media cache handler, so that the accept-webp is included in the meida cache [key]

**Comment by Antonytm** [comment]
@kudumulanarenderreddy @Halling69 
Issue is that  extension=webp query is cut by request protection. Adding of 
`<parameter description="extension" name="extension"/>` to _sitecore>mediaLibrary>requestProtection>protectedMediaQueryParameters_ fixes the issue

**Comment by Halling69** [comment]
@Antonytm 
When configured to run on CDN, you need to add: 
  <sitecore>
    <settings>
      
      <setting name="MediaResponse.VaryHeader" value="User-Agent"/>

Else the CDN will cache the first served image, either the webp-version or the jpeg/png version, depending on which browser type that triggers the first CDN fetch from origin
