### ISSUE TITLE
Scaling WebP images fail in synchronously mode.

### ISSUE THREAD

**Issue by jbluemink** [kamsar/Dianoga#53]
With the latest source and Dianoga.Strategy.GetMediaStreamSync.config
scaling WebP images fail In synchronously mode.
If the first request to a media with scaling parameters with a WebP Accept header you get the original uploaded image back, not scaled.

In the log file you see somethings like this:
8764 13:51:08 INFO  Dianoga: optimized /Images/Doner.jpeg [original size] (final size: 12534 bytes) - saved 18461 bytes / 59.56 %. Optimized in 157ms.
8764 13:51:08 ERROR Could not run the 'getMediaStream' pipeline for '/sitecore/media library/Images/Doner'. Original media data will be used.
Exception: System.ArgumentException
Message: Parameter is not valid.
Source: System.Drawing
   at System.Drawing.Bitmap..ctor(Stream stream)
   at Sitecore.Resources.Media.SaveColorProfileProcessor.Process(GetMediaStreamPipelineArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Resources.Media.Media.GetStreamFromPipeline(MediaOptions options, Boolean& canBeCached)
   
  
  Reproduction.
  - Install Dianoga from latest source, 
  - enable WebP.config
  - enable GetMediaStreamSync mode
  - clear media cache
  - do a valid request with accept WebP header to a jpg media in Sitecore with scaling parameters for example /-/media/Images/Doner.ashx?h=50&w=70&hash=7C0CD542B2833FC370CE13DD90C54FAE
Result error in log, original uploaded media instead of scaled WebP Image.

When you first hit to the image (with the scaling parameters)  is a non WebP request, then it can works okay.

**Comment by alexander-nanay** [comment]
Looks like optimization pipeline is executed 2 times:
1. Get original file
2. Get scaled image based on 1st

Second step gets webp instead of png (or jpeg) so it can't scale.
Somehow if original png is already in the MediaCache then 2nd step will work fine.
It seems like correct behavior would be to not apply webp conversion during first part.

Unfortunately I could not translate hypothesis into code and make a proper PR so far, so I've applied a workaround to not apply webp optimization on scaling requests - extend `ParseAcceptHeaders` and bind new class through `Dianoga.WebP.config`.

``` 
public class ParseMediaRequest : ParseAcceptHeaders
{
	public override bool BrowserSupportWebP
	{
		get
		{
			bool imageScalingRequest =
				HttpContext.Current != null &&
				(HttpContext.Current.Request.QueryString.Get("w") != null ||
				 HttpContext.Current.Request.QueryString.Get("h") != null);

			// do not apply webp for scaling requests until this one is fixed 
			// https://github.com/kamsar/Dianoga/issues/53
			return !imageScalingRequest && base.BrowserSupportWebP;
		}
		set { base.BrowserSupportWebP = value; }
	}
}  
```

**Comment by HageMaster3108** [comment]
Other folks have solved it like this:
https://sitecore.stackexchange.com/questions/1674/error-could-not-run-the-getmediastream-pipeline-for-x-when-loading-images/2148#2148

**Comment by markgibbons25** [comment]
I can also reproduce this issue. The link above from HageMaster makes no difference as that code is in sitecore 9.0+ now from what I can see (even 8.2 is the same for this discussion).

**Comment by HageMaster3108** [comment]
I can't confirm that @markgibbons25.
My vanilla 9.1.1 instance still aborts in SaveColorProfileProcessor because of the color-profile related exception.

**Comment by markgibbons25** [comment]
Yes, I can reproduce it with or without the SaveColorProfileProcessor pipeline code from [here](https://sitecore.stackexchange.com/a/2148/1278) I'm just saying that code seems to be in Sitecore.Kernel since at least 8.2.5, I would guess from the date that answer was posted they were on Sitecore 8.1 or an early version of 8.2

**Comment by markgibbons25** [comment]
This is now resolved https://github.com/kamsar/Dianoga/releases/tag/5.0.0-beta.1
